let a = 42;
let b = "Bonjour";
let c = true;
let d = null;
let e;
let f = [1, 2, 3];
let g = { nom: "Ali" };
let h = NaN;
console.log( typeof a);
console.log( typeof b);
console.log( typeof c);
console.log( typeof d);
console.log( typeof e);
console.log( typeof f);
console.log( typeof g);
console.log( typeof h);